# Global base mise config

[tools]
# Stack
rust = "latest"

# Tools
usage = "latest"                                         # Usage command
cargo-binstall = "latest"                                # Install Rust binaries from GitHub releases
just = "latest"                                          # Better make
ripgrep = "latest"                                       # Better grep
fd = "latest"                                            # Better find
bat = "latest"                                           # Better cat
"watchexec" = "latest"                                   # Watch fs changes and run commands
"cargo:exa" = "latest"                                   # Better ls
"cargo:jaq" = "latest"                                   # Oxidized jq
"cargo:xsv" = "latest"                                   # CSV processor CLI
"cargo:https://github.com/tekumara/typos-lsp" = "latest" # LSP server for typos

[settings]
experimental = true   # Enable extra features
cargo.binstall = true # Enable cargo binstall
