[tools]
## Stack
rust = "latest"

## Tools
# Usage command
usage = "latest"
# Install Rust-based binaries instead of compiling
cargo-binstall = "latest"
# Better make
just = "latest"
# Better grep
ripgrep = "latest"
# Better find
fd = "latest"
# Better cat
bat = "latest"
# Better ls
"cargo:exa" = "latest"

[settings]
# Enable extra features
experimental = true
# Enable cargo binstall
cargo.binstall = true
