[tools]
# Shell
starship = "latest"
# Stack
rust = "latest"
# Tools
cargo-binstall = "latest"
"cargo:just" = "latest"
"cargo:https://github.com/tekumara/typos-lsp" = "latest"
# Espressif
"cargo:cargo-espflash" = "latest"
"cargo:espflash" = "latest"
"cargo:ldproxy" = "latest"

[settings]
experimental = true
cargo.binstall = true
idiomatic_version_file_enable_tools = ["rust"]
