[tools]
# Stack
node = "lts"
# Tools
# Dev Container CLI
"npm:@devcontainers/cli" = "latest"
just = "latest"
# AI
"npm:@anthropic-ai/claude-code" = "latest"

[env]
_.file = '.env.maintain'

[settings]
experimental = true
