[tools]
# Shell
starship = "latest"
# Stack
node = { version = "latest", postinstall = "corepack enable" }
rust = "latest"
# Tools
cargo-binstall = "latest"
"cargo:just" = "latest"
"cargo:https://github.com/tekumara/typos-lsp" = "latest"
# TODO: Figure out why it fails to install:
# "npm:@devcontainers/cli" = "latest"

[hooks]
postinstall = "just --completions fish > ~/.config/fish/completions/just.fish"

[settings]
experimental = true
cargo.binstall = true
idiomatic_version_file_enable_tools = ["node", "rust"]
