# Global Go mise config

[tools]
## Stack
rust = "latest"
go = "latest"

## Tools
# Usage command
usage = "latest"
# Install Rust-based binaries instead of compiling
cargo-binstall = "latest"
# Better make
just = "latest"
# Better grep
ripgrep = "latest"
# Better find
fd = "latest"
# Better cat
bat = "latest"
# Better ls
"cargo:exa" = "latest"
# Oxidized jq
"cargo:jaq" = "latest"

[settings]
# Enable extra features
experimental = true
# Enable cargo binstall
cargo.binstall = true
# Use rust-toolchain.toml, .go-version, etc.
idiomatic_version_file_enable_tools = ["rust", "go"]
