---
- name: Set up age
  hosts: localhost
  connection: local

  tasks:
    - name: Debian/Ubuntu set up
      when: ansible_os_family == "Debian"
      become: yes
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: Install age
          apt:
            name: age
            state: present

    - name: macOS set up
      when: ansible_system == "Darwin"
      block:
        - name: Update Homebrew
          homebrew:
            update_homebrew: true

        - name: Install age
          homebrew:
            name: age
            state: present
