---
- name: Set up chezmoi
  hosts: localhost
  connection: local

  tasks:
    - name: Install chezmoi
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b {{ ansible_env.HOME }}/.local/bin
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/chezmoi"

    - name: Set up ~/.local/bin in PATH
      include: local-bin.yaml

    - name: Initialize dotfiles
      when: ansible_env.GITHUB_USERNAME is defined
      shell: "chezmoi init --apply {{ ansible_env.GITHUB_USERNAME }} --force"
      args:
        creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"
