---
- name: Set up mise
  hosts: localhost
  connection: local

  tasks:
    - name: Install mise
      shell: curl https://mise.run | sh
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/mise"

    - name: Set up fish shell
      lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "mise activate fish | source"
        create: yes

    - name: Install usage
      shell: |
        export PATH="$HOME/.local/bin:$PATH"
        mise ls usage || mise use -g usage
      changed_when: false

    - name: Add fish completions
      shell: "mise completion fish > {{ ansible_env.HOME }}/.config/fish/completions/mise.fish"
      args:
        creates: "{{ ansible_env.HOME }}/.config/fish/completions/mise.fish"
