---
- name: Set up mise
  hosts: localhost
  connection: local

  tasks:
    - name: Install mise
      shell: curl https://mise.run | sh
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/mise"

    - name: Set up ~/.local/bin in PATH
      include_tasks: local-bin-tasks.yaml

    - name: Set up bash shell
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'eval "$(mise activate bash)"'
        create: yes

    - name: Set up zsh shell
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'eval "$(mise activate zsh)"'
        create: yes

    - name: Set up fish shell
      lineinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        line: "mise activate fish | source"
        create: yes

    - name: Install usage
      shell: |
        export PATH="$HOME/.local/bin:$PATH"
        mise ls usage || mise use -g usage
      changed_when: false

    - name: Create fish completions directory
      file:
        path: "{{ ansible_env.HOME }}/.config/fish/completions"
        state: directory

    - name: Add fish completions
      shell: |
        export PATH="$HOME/.local/bin:$PATH"
        mise completion fish > {{ ansible_env.HOME }}/.config/fish/completions/mise.fish
      args:
        creates: "{{ ansible_env.HOME }}/.config/fish/completions/mise.fish"
