---
- name: Setup development machine
  hosts: localhost
  connection: local

  tasks:
    - name: Update apt cache
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Homebrew (macOS)
      when: ansible_system == "Darwin"
      become: yes
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /opt/homebrew/bin/brew

    - name: Update Homebrew (macOS)
      homebrew:
        update_homebrew: true

    - name: Install fish (Debian)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name: fish
        state: present

    - name: Install fish (macOS)
      when: ansible_system == "Darwin"
      homebrew:
        name: fish
        state: present

    - name: Get local user
      local_action: command whoami
      register: whoami_result

    - name: Set local user fact
      set_fact:
        local_user: "{{ whoami_result.stdout }}"

    - name: Set fish as default shell (Linux)
      when: ansible_system == "Linux"
      become: yes
      user:
        name: "{{ local_user }}"
        shell: /usr/bin/fish

    - name: Add fish to /etc/shells (macOS)
      when: ansible_system == "Darwin"
      become: yes
      lineinfile:
        path: /etc/shells
        line: /opt/homebrew/bin/fish
        state: present

    - name: Set fish as default shell (macOS)
      when: ansible_system == "Darwin"
      become: yes
      command: "chsh -s /opt/homebrew/bin/fish {{ local_user }}"
      register: chsh_result
      changed_when: chsh_result.rc == 0

    - name: Install Starship
      become: yes
      shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes
      args:
        creates: /usr/local/bin/starship

    - name: Install chezmoi
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b {{ ansible_env.HOME }}/.local/bin
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/chezmoi"

    - name: Initialize dotfiles
      shell: chezmoi init --apply kossnocorp
      args:
        creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"
